Wiki\AdminBundle\Entity\projet:
    type: entity
    table: null
    repositoryClass: Wiki\AdminBundle\Entity\projetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        date:
            type: date
        title:
            type: string
            length: 255
        content:
            type: string
            length: 255
        author:
            type: string
            length: 255
    lifecycleCallbacks: {  }
