Wiki\WikiMaireBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: Wiki\WikiMaireBundle\Entity\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        comment:
            type: string
            length: 255
        date:
            type: date

    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: maire_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
