Wiki\WikiMaireBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: Wiki\WikiMaireBundle\Entity\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomprojet:
            type: string
            length: 255
        commune:
            type: string
            length: 255
        entrepreneur:
            type: string
            length: 255
        cout:
            type: float
        date:
            type: date
        description:
            type: string
            length: 255
        difficulte:
            type: string
            length: 255
    lifecycleCallbacks: {  }
