Wiki\WikiMaireBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: Wiki\WikiMaireBundle\Entity\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomprojet:
            type: string
            length: 255
        description:
            type: string
            length: 255
        duree:
            type: string
            length: 255
        gains:
            type: string
            length: string
        daterealisation:
            type: date
        cout:
            type: float
        photo:
            type: string
            length: 255
        financement:
            type: string
            length: 255
            nullable: true





    manyToOne:
        user:
            targetEntity: Application\Sonata\UserBundle\Entity\User
            joinColumn:
                name: maire_id
                referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [ preUpload ]
        preUpdate: [ preUpload ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]
