commune:
    path:     /
    defaults: { _controller: "WikiAdminBundle:Commune:index" }

commune_show:
    path:     /{id}/show
    defaults: { _controller: "WikiAdminBundle:Commune:show" }

commune_new:
    path:     /new
    defaults: { _controller: "WikiAdminBundle:Commune:new" }

commune_create:
    path:     /create
    defaults: { _controller: "WikiAdminBundle:Commune:create" }
    methods:  POST

commune_edit:
    path:     /{id}/edit
    defaults: { _controller: "WikiAdminBundle:Commune:edit" }

commune_update:
    path:     /{id}/update
    defaults: { _controller: "WikiAdminBundle:Commune:update" }
    methods:  [POST, PUT]

commune_delete:
    path:     /{id}/delete
    defaults: { _controller: "WikiAdminBundle:Commune:delete" }
    methods:  [POST, DELETE]
