wiki_wiki_maire_homepage:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  [POST, GET]


contact:
    path:     /contact
    defaults: { _controller: "AppBundle:Default:contact" }
    methods:  [POST, GET]

