wiki_wiki_maire_homepage:
    path:     /hello/{name}
    defaults: { _controller: WikiWikiMaireBundle:Default:index }

ajout:
    path:     /projet/add
    defaults: { _controller: WikiWikiMaireBundle:Projet:index }
