wiki_wiki_maire_projet:
    resource: "@WikiWikiMaireBundle/Resources/config/routing/projet.yml"
    prefix:   /projet



wiki_wiki_maire_homepage:
    path:     /
    defaults: { _controller: WikiWikiMaireBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: WikiWikiMaireBundle:Default:contact }

