services:
#    wiki_wiki_maire.example:
#        class: Wiki\WikiMaireBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    wiki_wiki_maire.admin.commune:
        class: Wiki\WikiMaireBundle\Admin\CommuneAdmin
        arguments: [~, Wiki\WikiMaireBundle\Entity\Commune, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Communes, label: Communes}
