wiki_admin_commune:
    resource: "@WikiAdminBundle/Resources/config/routing/commune.yml"
    prefix:   /commune

wiki_admin_users:
    resource: "@WikiAdminBundle/Resources/config/routing/users.yml"
    prefix:   /users

homepage:
    path:     /
    defaults: { _controller: WikiAdminBundle:default:index }

add:
    path:     /projet
    defaults: { _controller: WikiAdminBundle:projet:add }
