# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

#services:
#    admin.projet:
#        class: Wiki\WikiMaireBundle\Admin\ProjetAdmin
#        arguments: [~, Wiki\WikiMaireBundle\Entity\Projet, ~]
#        tags:
#            - { name: sonata.admin, manager_type: orm,  group: "Projet", label: Projet }

services:
    admin_success_handler:
        class: Wiki\WikiMaireBundle\Services\AuthenticationHandler
        arguments: [@router]

    sonata.user.admin.group:
        abstract: true
        public: false