# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value



services:
    admin_success_handler:
        class: Wiki\WikiMaireBundle\Services\AuthenticationHandler
        arguments: [@router]

    admin.projet:
        class: Wiki\WikiMaireBundle\Admin\ProjetAdmin
        arguments: [~, Wiki\WikiMaireBundle\Entity\Projet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm,  group: "Liste des Projets", label: 'Projet' }


    sonata.user.admin.group:
        abstract: true
        public: false

    login_listener:
        class: 'Application\Sonata\UserBundle\EventListener\LoginListener'
        arguments: ['@security.context', '@router', '@event_dispatcher']
        tags:
           - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }