projet:
    path:     /
    defaults: { _controller: "WikiWikiMaireBundle:Projet:index" }

projet_create:
    path:     /create
    defaults: { _controller: "WikiWikiMaireBundle:Projet:create" }
    methods:  [POST, GET]

projet_edit:
    path:     /{id}/edit
    defaults: { _controller: "WikiWikiMaireBundle:Projet:edit" }

projet_update:
    path:     /{id}/update
    defaults: { _controller: "WikiWikiMaireBundle:Projet:update" }
    methods:  [POST, PUT]

projet_delete:
    path:     /{id}/delete
    defaults: { _controller: "WikiWikiMaireBundle:Projet:delete" }
    methods:  [POST, GET]

projet_detail:
    path:     /{id}/detail
    defaults: { _controller: "WikiWikiMaireBundle:Projet:detail" }
    methods:  [POST, GET]


projet_recherche:
    path:     /{id}/recherche
    defaults: { _controller: "WikiWikiMaireBundle:Projet:Recherche" }
    methods:  [POST, GET]